### PR TITLE
Added graphql based implementation

### PR DESCRIPTION
**Pull request by Presto412**

### CODE REVIEW

**Comment by paazmaya** [comment]
@hound you are not helping.

Some issues with unit test coverage degreasing, but lets figure that out last, when implementation is ready.

**Comment by Presto412** [comment]
Sure

**Comment by Presto412** [comment]
Hey, were you able to try it out?

**Comment by paazmaya** [comment]
Trying it out..

**Comment by paazmaya** [comment]
```json
{
    "fork": false,
    "owner": {
      "login": "paazmaya"
    },
    "name": "PaazioTools",
    "ssh_url": "git@github.com:paazmaya/PaazioTools.git",
    "parent": {
      "ssh_url": null
    }
  }
```

Finally got back on this, and the above is what the API currently gives. I will try to tune that to contain more info...

**Comment by paazmaya** [comment]
I have a repo now https://github.com/paazmaya/kibana, which is a fork from https://github.com/katrin-freihofner/kibana, which is a fork from https://github.com/elastic/kibana

```json

{
            "nameWithOwner": "paazmaya/kibana",
            "sshUrl": "git@github.com:paazmaya/kibana.git",
            "isFork": true,
            "parent": {
              "isFork": true,
              "sshUrl": "git@github.com:katrin-freihofner/kibana.git",
              "parent": {
                "isFork": false,
                "sshUrl": "git@github.com:elastic/kibana.git"
              }
            }
}
```

Looks like there would need to be recursive `parent`, as many as one would just write.

I have not heard anyone using that feature, hence I think your PR is feature complete.

**Comment by paazmaya** [comment]
I added a commit  to `Presto412-master` branch to update the documentation a bit, hopefully that could help...

**Comment by Presto412** [comment]
You may not have pushed it, I can't see any new commits

**Comment by Presto412** [comment]
Alright! Thanks for giving me the chance to contribute! Happy hacktoberfest!
Let me know if there is anything else I can help with.

**Comment by Presto412** [comment]
So I've removed the extra files and added a sample unit test. The credentials provided in the existing tests give out a "Bad Credentials" error, so please add some credentials. (works when I use my own personal access token)

Moreover, I've added a comment here, and can't seem to figure out why using nock is going wrong. If you could help out [here](https://github.com/Presto412/maezato/blob/9729d5964b0fbe2fa2599b5f1f5049dfa2c27f6c/tests/lib/get-repos-graphql_test.js#L42), would be great

We can resolve the failed tests once that is clear

**Comment by paazmaya** [comment]
Trying to solve it...

**Pull request merged**
